### PR TITLE
ddcc to shc mappings

### PR DESCRIPTION
**Pull request by nkarip**
Includes ddcc-to-shc and shc-to-ddcc core data set VS mappings, as well as HTML documentation of mapping equivalence.

### CODE REVIEW

**Comment by litlfred** [comment]
@lukeaduncan

**Comment by lukeaduncan** [comment]
@nkarip @litlfred There were too many conflicts to resolve due to concurrent updates.  I tried to pull in the new files, but please confirm from the main branch to see if everything is there that needs to be and submit a new pull request if anything is missing.

Thanks!

**Comment by litlfred** [comment]
@lukeaduncan any chance at looking at this to get this merged?

**Comment by lukeaduncan** [comment]
> @lukeaduncan any chance at looking at this to get this merged?

There are conflicts that need to be fixed before I can merge this.

**Comment by nkarip** [comment]
Closing as outdated

**Pull request closed without merging**
